In [10]:
import collections
from random import choice

Card = collections.namedtuple('Card', ['rank','suit'])


class FrenchDeck:
    ranks = [str(n) for n in range(2, 11)] + list('JQKA')
    suits = 'spades diamonds clubs hearts'.split()

    def __init__(self):
        self._cards = [Card(rank, suit) for suit in self.suits
                                       for rank in self.ranks]
    
    def __len__(self):
        return len(self._cards)
    
    def __getitem__(self, position):
        return self._cards[position]
    
    def random_card(self):
        return choice(self._cards)

# Note: this FrenchDeck is immutable, because it only has __getitem__ and __len__ methods

In [ ]:
# list comprehension examples
[str(n) for n in range(2, 11)] + list('JQKA')
[Card(rank, suit) for suit in FrenchDeck.suits for rank in FrenchDeck.ranks]

In [ ]:
# __getitem__ example
deck = FrenchDeck()
print(f'Select index 5: {deck[5]}')

# benefits of implementing the __getitem__ method
print(f'Retrieve the first 3 cards: {deck[:3]}') # slicing
print(f'Pick cards by rank: {deck[12::13]}') # picking cards by rank

for card in deck: # iterting over the deck
    print(card)

In [ ]:
# random_choice example
print(deck.random_card())

In [22]:
# ranking and sorting the cards
suit_values = dict(spades=3, hearts=2, diamonds=1, clubs=0)
def spades_high(card):
    rank_value = FrenchDeck.ranks.index(card.rank) # get the index of the card rank 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, J, Q, K, A
    return rank_value * len(suit_values) + suit_values[card.suit] # multiply the rank value by the length of the suit values and add the suit value ex. 0 * 4 + 3 = 3

print("Sorted cards: ", [card for card in sorted(deck, key=spades_high)])

Sorted cards:  [Card(rank='2', suit='clubs'), Card(rank='2', suit='diamonds'), Card(rank='2', suit='hearts'), Card(rank='2', suit='spades'), Card(rank='3', suit='clubs'), Card(rank='3', suit='diamonds'), Card(rank='3', suit='hearts'), Card(rank='3', suit='spades'), Card(rank='4', suit='clubs'), Card(rank='4', suit='diamonds'), Card(rank='4', suit='hearts'), Card(rank='4', suit='spades'), Card(rank='5', suit='clubs'), Card(rank='5', suit='diamonds'), Card(rank='5', suit='hearts'), Card(rank='5', suit='spades'), Card(rank='6', suit='clubs'), Card(rank='6', suit='diamonds'), Card(rank='6', suit='hearts'), Card(rank='6', suit='spades'), Card(rank='7', suit='clubs'), Card(rank='7', suit='diamonds'), Card(rank='7', suit='hearts'), Card(rank='7', suit='spades'), Card(rank='8', suit='clubs'), Card(rank='8', suit='diamonds'), Card(rank='8', suit='hearts'), Card(rank='8', suit='spades'), Card(rank='9', suit='clubs'), Card(rank='9', suit='diamonds'), Card(rank='9', suit='hearts'), Card(rank='9', 

In [ ]:
from math import hypot

class Vector:
    def __init__(self, x=0, y=0):
        self.x = x
        self.y = y
        
    def __repr__(self):
        return f'Vector({self.x}, {self.y})'
    
    def __abs__(self):
        return hypot(self.x, self.y)
    
    def __bool__(self):
        return bool(abs(self))
    
    def __add__(self, other):
        x = self.x + other.x
        y = self.y +other.y
        return Vector(x, y=y)
    
    def __mul__(self, scalar):
        return Vector(self.x * scalar, self.y * scalar)
    
    
    
    

In [ ]:
# Sequences in Python

In [1]:
# List Comprehensions and Generator Expressions
alphabet = 'abcdefghijklmnopqrstuvwxyz'
alphabet_codes = [ord(letter) for letter in alphabet]
print(alphabet_codes)

[97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122]


In [9]:
# Tuples: Immutable? Yes, but only on the surface
# Tuple Unpacking
# parallel assignment - assigning items from an iterable to a tuple of variables, useful for swapping values of variables without a temporary variable
# Using * to grab excess items or when calling a function

a, b, *rest = range(5)
print(a, b, rest) # 0 1 [2, 3, 4]

[*range(4), 4] # 0, 1, 2, 3, 4
[range(4), 4] # [range(0, 4), 4]

0 1 [2, 3, 4]


[range(0, 4), 4]

In [ ]:
# Pattern matching with sequences

match subject:
    case <pattern_1>:
        <action_1>
    case <pattern_2>:
        <action_2>
    case <pattern_3>:
        <action_3>
    case _:
        <action_wildcard>

In [17]:
class Point:
    x: int
    y: int

    def __init__(self, x, y):
        self.x = x
        self.y = y

def location(point):
    match point:
        case Point(x=0, y=0):
            print("Origin is the point's location.")
        case Point(x=0, y=y):
            print(f"Y={y} and the point is on the y-axis.")
        case Point(x=x, y=0):
            print(f"X={x} and the point is on the x-axis.")
        case Point():
            print("The point is located somewhere else on the plane.")
        case _:
            print("Not a point")
            
point = Point(0,0)
location(point)

Origin is the point's location.


In [ ]:
# Example 2-9. Method from an imaginary Robot class


In [21]:
# Initializing a list with a certain number of nested lists
board = [['_'] * 3 for i in range(3)]
print(board)
weird_board = [['_'] * 3] * 3
print(weird_board)
weird_board[1][2] = 'O'
print(weird_board)

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]
[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]
[['_', '_', 'O'], ['_', '_', 'O'], ['_', '_', 'O']]


In [23]:
# Sorting

fruits = ['grape', 'raspberry', 'apple', 'banana']
sorted_fruits = sorted(fruits)
print(sorted_fruits)
print(fruits)
fruits.sort()
print(fruits)

fruits = ['grape', 'raspberry', 'apple', 'banana']
sorted_fruits_by_length = sorted(fruits, key=len)
print(sorted_fruits_by_length)

['apple', 'banana', 'grape', 'raspberry']
['grape', 'raspberry', 'apple', 'banana']
['apple', 'banana', 'grape', 'raspberry']
['grape', 'apple', 'banana', 'raspberry']


In [24]:
# Bisect - uses the binary search algorithm to find (bisect) and insert (insort) items in a sorted list. 
import bisect
import sys

HAYSTACK = [1,4,5,6,8,12,15,20,21,23,23,26,29,30]
NEEDLES = [0,1,2,5,8,10,22,23,29,30,31]

ROW_FMT = '{0:2d} @ {1:2d}    {2}{0:<2d}' # format for printing the needle, position, and offset

def demo(bisect_fn):
    for needle in reversed(NEEDLES):
        position = bisect_fn(HAYSTACK, needle) # search for the needle in the haystack
        offset = position * '  |' # create the offset
        print(ROW_FMT.format(needle, position, offset)) # print the needle, position, and offset

if __name__ == '__main__':
    if sys.argv[-1] == 'left':
        bisect_fn = bisect.bisect_left
    else:
        bisect_fn = bisect.bisect
    
    print('DEMO:', bisect_fn.__name__)
    print('haystack ->', ' '.join('%2d' % n for n in HAYSTACK))
    demo(bisect_fn)


DEMO: bisect_right
haystack ->  1  4  5  6  8 12 15 20 21 23 23 26 29 30
31 @ 14      |  |  |  |  |  |  |  |  |  |  |  |  |  |31
30 @ 14      |  |  |  |  |  |  |  |  |  |  |  |  |  |30
29 @ 13      |  |  |  |  |  |  |  |  |  |  |  |  |29
23 @ 11      |  |  |  |  |  |  |  |  |  |  |23
22 @  9      |  |  |  |  |  |  |  |  |22
10 @  5      |  |  |  |  |10
 8 @  5      |  |  |  |  |8 
 5 @  3      |  |  |5 
 2 @  1      |2 
 1 @  1      |1 
 0 @  0    0 


In [25]:
# Example 2-18. Given a test score, grade returns the corresponding letter grade
def grade(score, breakpoints=[60,70,80,90], grades='FDCBA'):
    i = bisect.bisect(breakpoints, score)
    return grades[i]

[grade(score) for score in [33, 99, 77, 70, 89, 90, 100]]

['F', 'A', 'C', 'C', 'B', 'A', 'A']

In [26]:
# Example 2-19. Insort keeps a sorted sequence always sorted
import bisect
import random

SIZE = 7

random.seed(1729)

my_list = []
for i in range(SIZE):
    new_item = random.randrange(SIZE*2)
    bisect.insort(my_list, new_item)
    print('%2d ->' % new_item, my_list)
    


10 -> [10]
 0 -> [0, 10]
 6 -> [0, 6, 10]
 8 -> [0, 6, 8, 10]
 7 -> [0, 6, 7, 8, 10]
 2 -> [0, 2, 6, 7, 8, 10]
10 -> [0, 2, 6, 7, 8, 10, 10]


In [ ]:
# Arrays
from array import array
from random import random

# Example 2-20. Creating, saving, and loading a large array of floats
floats = array('d', (random() for i in range(10**7))) # type code 'd' is for double-precision floating-point numbers
print(floats[-1])

fp = open('floats.bin', 'wb') # open the file in binary mode
floats.tofile(fp)
fp.close()

floats2 = array('d') # create an array of doubles
fp = open('floats.bin', 'rb')
floats2.fromfile(fp, 10**7) # read 10 million numbers from the binary file
fp.close()

print(floats2[-1])
print(floats2 == floats)

# saving with array.tofile and loading with array.fromfile is about 60 times faster than using 
# pickle.dump and pickle.load

0.1288579230853678
0.1288579230853678
True


In [32]:
# Memory View - built-in Python memoryview class is a shared-memory sequence type that lets you 
# handle slices of arrays without copying bytes

numbers = array('h', [-2, -1, 0, 1, 2]) # type code 'h' is for signed short integers
memv = memoryview(numbers) # create a memory view on the array of short integers
print(len(memv))

print(memv[0])

memv_oct = memv.cast('B') # create a memory view of unsigned bytes
memv_oct.tolist() # convert the memory view to a list of integers

memv_oct[5] = 4 # change the 6th byte in the unsigned bytes memory view
print(memv_oct)

5
-2


In [35]:
import numpy as np
# Basic Numpy Operations
a = np.arange(12)
print(a) # array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])
print(type(a)) # <class 'numpy.ndarray'>
print(a.shape) # (12,)

a.shape = 3, 4
print(a) # array([[ 0,  1,  2,  3], [ 4,  5,  6,  7], [ 8,  9, 10, 11]])
print(a[2]) # array([8, 9, 10, 11])
print(a[2,1]) # 9
print(a[:,1]) # array([1, 5, 9])
print(a.transpose()) # array([[ 0,  4,  8], [ 1,  5,  9], [ 2,  6, 10], [ 3,  7, 11]])
print(a.transpose().shape) # (4, 3)


[ 0  1  2  3  4  5  6  7  8  9 10 11]
<class 'numpy.ndarray'>
(12,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 8  9 10 11]
9
[1 5 9]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
(4, 3)


In [43]:
# Deques - double-ended queues
# Example 2-23. Working with a deque

from collections import deque
dq = deque(range(10), maxlen=10) # create a deque with 10 items
print(dq)
dq.rotate(3) # rotate the deque 3 steps to the right
print(dq) # deque([7, 8, 9, 0, 1, 2, 3, 4, 5, 6], maxlen=10)

dq.rotate(-4) 
print(dq) # deque([1, 2, 3, 4, 5, 6, 7, 8, 9, 0], maxlen=10)

dq.appendleft(-1) # add -1 to the left
print(dq) # deque([-1, 1, 2, 3, 4, 5, 6, 7, 8, 9], maxlen=10)

dq.extend([11, 22, 33])  # add three items to the right
print(dq) # deque([3, 4, 5, 6, 7, 8, 9, 11, 22, 33], maxlen=10)

dq.extendleft([10, 20, 30, 40]) # add four items to the left
print(dq) # deque([40, 30, 20, 10, 3, 4, 5, 6, 7, 8], maxlen=10)

# other queue libraries: queue, multiprocessing, asyncio, heapq, sched, and asyncio



deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], maxlen=10)
deque([7, 8, 9, 0, 1, 2, 3, 4, 5, 6], maxlen=10)
deque([1, 2, 3, 4, 5, 6, 7, 8, 9, 0], maxlen=10)
deque([-1, 1, 2, 3, 4, 5, 6, 7, 8, 9], maxlen=10)
deque([3, 4, 5, 6, 7, 8, 9, 11, 22, 33], maxlen=10)
deque([40, 30, 20, 10, 3, 4, 5, 6, 7, 8], maxlen=10)


In [44]:
# __eq__ note. __eq__ is a special method that is stands for "equals." 
# It is used to define the behavior of the equality operator = for instances of a class. 
# by default it compares obj references, meaning two objects are only 
# equal if they are the same object in memory. 

class Point:
    def __init__(self, x, y):
        self.x = x
        self.y = y
        
p1 = Point(1, 2)
p2 = Point(1, 2)
print(p1 == p2) # False
print(p1 is p2) # False

# Though p1 and p2 share attributes, they do not share the same memory location.
# To make the comparison work, you need to implement the __eq__ method in the Point class.


False
False


In [45]:
class Point: 
    def __init__(self, x, y):
        self.x = x
        self.y = y
        
    def __eq__(self, other):
        return self.x == other.x and self.y == other.y
    
p1 = Point(1, 2)
p2 = Point(1, 2)
print(p1 == p2) # True
print(p1 is p2) # False, because the "is" operator checks that the variables reference the same memory address

True
False


In [49]:
# What is hashable?
t1 = (1, 2, (30, 40))
t2 = (1, 2, [30, 40])
print(hash(t1)) 
# print(hash(t2)) # TypeError: unhashable type: 'list'

t3 = (1, 2, frozenset([30, 40]))
print(hash(t3))

-3907003130834322577
5149391500123939311


In [ ]:
# Building dictionaries
a = dict(one=1, two=2, three=3)
b = {'one': 1, 'two': 2, 'three': 3}
c = dict(zip(['one', 'two', 'three'], [1, 2, 3]))
d = dict([('two', 2), ('one', 1), ('three', 3)])
e = dict({'three': 3, 'one': 1, 'two': 2})

# Why would you ever select e over b?
# If you're working with a subclass of a dict, and you want to 
# explicitly pass an existing dictionary to the constructor to enforce the type.
# But actually, you most likely wouldn't use e, because it's less readable than b.

In [50]:
# Dictcomp
DIAL_CODES = [
    (86, 'China'),
    (91, 'India'),
    (1, 'United States'),
    (62, 'Indonesia'),
    (55, 'Brazil'),
    (92, 'Pakistan'),
    (880, 'Bangladesh'),
    (234, 'Nigeria'),
    (7, 'Russia'),
    (81, 'Japan')
]

country_code = {country: code for code, country in DIAL_CODES}
print(country_code)

print({code: country.upper() for country, code in country_code.items() if code < 66})

{'China': 86, 'India': 91, 'United States': 1, 'Indonesia': 62, 'Brazil': 55, 'Pakistan': 92, 'Bangladesh': 880, 'Nigeria': 234, 'Russia': 7, 'Japan': 81}
{1: 'UNITED STATES', 62: 'INDONESIA', 55: 'BRAZIL', 7: 'RUSSIA'}


In [67]:
# Examples of strengths of using update()

# 1. Merging dictionaries
a = {'x': 1, 'y': 2}
b = {'y': 3, 'z': 4}
a.update(b)
print(a) 

# 2. Adding key-value pairs from iterable
d = {'a': 1}
new_items = [('b', 2), ('c', 3)]
d.update(new_items)
print(d) # {'a': 1, 'b': 2, 'c': 3}

# 3. Using update with keyword arguments
d = {'x': 10}
d.update(y=20, z=30)
print(d) # {'x': 10, 'y': 20, 'z': 30}

# Overwriting and adding multiple levels
d = {'a': {'nested': 1}, 'b': 2}
updates = {'a': {'nested':2}, 'c': 3}
d.update(updates)
print(d) # {'a': {'nested': 2}, 'b': 2, 'c': 3}


{'x': 1, 'y': 3, 'z': 4}
{'a': 1, 'b': 2, 'c': 3}
{'x': 10, 'y': 20, 'z': 30}
{'a': {'nested': 2}, 'b': 2, 'c': 3}


In [53]:
# When and how to use setdefault
# d[k] raises an error when k is not an existing key.
# d.get(k, default) returns the value of k if it exists, otherwise it returns default.
# But d.get() can be awkward and inefficient.

words = ['apple', 'bat', 'bar', 'atom', 'book', 'bat', 'atom', 'apple', 'atom']
word_count = {}

for word in words:
    word_count.setdefault(word, 0)
    word_count[word] += 1
    
print(word_count)

# unlike .append, which searches the key at least twice, setdefault searches the key once all in a single loop.
# and unlike .get, setdefault sets the key if it doesn't exist.

d = {}
d.setdefault('table', 4)
print(d)

d.get('chair', 0)
print(d) # no changes made to dictionary

# .get() does not update the dictionary, but setdefault does!!


{'apple': 2, 'bat': 2, 'bar': 1, 'atom': 3, 'book': 1}
{'table': 4}
{'table': 4}


In [55]:
# defaultdict
# defaultdict is a subclass of dict that returns a default value when a key is not found.

# when instantiating a defaultdict, you provide a callable that is used to produce 
# default value whenever __getitem__ is passed a nonexistent key arg.

from collections import defaultdict
dd = defaultdict(list) # list is the callable
dd['key1']
print(dd) # defaultdict(<class 'list'>, {'key1': []})

# defaultdict is only invoked to provide values for __getitem__ calls. 
# d[k], if k is missing, will call the callable to create a default value, 
# but d.get(k) will return None.

# The method that makes this work is called __missing__.


defaultdict(<class 'list'>, {'key1': []})


In [ ]:
# converting nonstring keys to str on lookup
class StrKeyDict0(dict):
    def __missing__(self, key):
        if isinstance(key, str):
            raise KeyError(key)
        return self[str(key)]
    
    def get(self, key, default=None):
        try:
            return self[key]
        except KeyError:
            return default
        
    def __contains__(self, key):
        return key in self.keys() or str(key) in self.keys()
    
    # __contains__ is called by the in operator
    # __missing__ is called by the __getitem__ method (i.e., d[k])
    # get is called by the get method (i.e., d.get(k))
    # adding __contains__ is important because k in d does not call __missing__
    

In [56]:
# Variations of dict
# collections.OrderedDict - maintains keys in insertion order
# collections.ChainMap - holds a list of mappings that can be searched as one
# collections.Counter - a mapping that holds an integer count for each key
# collections.UserDict - a pure Python implementation of a mapping that works like a standard dict

from collections import Counter
ct = Counter('abracadabra')
print(ct) # Counter({'a': 5, 'b': 2, 'r': 2, 'c': 1, 'd': 1})
ct.update('aaaaazzz') # add more 'a's and 'z's
print(ct) # Counter({'a': 10, 'z': 3, 'b': 2, 'r': 2, 'c': 1, 'd': 1})
ct.most_common(2) # get the two most common elements

Counter({'a': 5, 'b': 2, 'r': 2, 'c': 1, 'd': 1})
Counter({'a': 10, 'z': 3, 'b': 2, 'r': 2, 'c': 1, 'd': 1})


[('a', 10), ('z', 3)]

In [ ]:
# It's preferable to subclass from UserDict rather than dict.
# UserDict does not inherit from dict, but has an internal dict instance called data.
# UserDict is a wrapper around the dictionary.
# You can override only the methods you need without worrying about breaking the other parts. 

# Example 3-8. StrKeyDict always converts non-string keys to str—on insertion, update, and lookup

import collections

class StrKeyDict(collections.UserDict):
    def __missing__(self, key):
        if isinstance(key, str):
            raise KeyError(key)
        return self[str(key)]
    
    def __contains__(self, key): 
        return str(key) in self.data
    
    def __setitem__(self, key, item): # __setitem__ converts any key to a string
        self.data[str(key)] = item
        
    # in this example, we inherited Mapping.get
        
# __setitem__ is called by d[k] = v

In [ ]:
# Immutable Mappings
# MappingProxyType - a read-only dict

# Example 3-9. MappingProxyType creates a read-only mappingproxy instance from a dict
from types import MappingProxyType
d = {1: 'A'}
d_proxy = MappingProxyType(d)
print(d_proxy)
print(d_proxy[1])
# d_proxy[2] = 'x' # TypeError: 'mappingproxy' object does not support item assignment
d[2] = 'B'
print(d_proxy) # {1: 'A', 2: 'B'}
print(d_proxy[2]) # B 

# d_proxy is a read-only view of d. It is dynamic, meaning that any changes in d are reflected in d_proxy.



In [ ]:
# sets
# set - a collection of unique objects

# exapmle
needles = set([1, 2, 3, 4, 5])
haystack = set([3, 4, 5, 6, 7, 8, 9])

found = len(needles & haystack)
print(found) # 3

found = needles.intersection(haystack)
print(found) # {3, 4, 5}

# If needles and haystack are not sets, the alternatives might be cheaper.
# For example, if needles is a list, the intersection operation is O(n),
# but if needles is a set, the operation is O(1).
# converting a list to a set is O(n), but it is worth it if you are 
# going to perform many intersections.


In [57]:
# There is no set literal syntax.
# {} always creates a dict, so you must use set() to create an empty set.

# You can create non-empty sets using a comma-separated sequence 
# of values inside curly braces.
non_empty_set = {1, 2, 3, 4, 5}
print(type(non_empty_set))

non_empty_dict = {1: 'A', 2: 'B', 3: 'C'}
print(type(non_empty_dict))

# Using the set literal is much faster than calling the constructor because
# when calling the constructor, Python has to look up the set name in the global scope,
# build a list, and then pass it to the constructor.

# A literal like {1, 2, 3} is processed using a specialized BUILD_SET bytecode,
# which is faster than calling the set constructor.

# there is no set literal for frozenset.

<class 'set'>
<class 'dict'>


In [59]:
# set comprehension examples
squares = {x ** 2 for x in range(10)}
print(squares)

evens = {x for x in range(10) if x % 2 == 0}
print(evens)

unique_chars = {char for char in 'The cat jumped onto the table.'}
print(unique_chars)

{0, 1, 64, 4, 36, 9, 16, 49, 81, 25}
{0, 2, 4, 6, 8}
{'e', 'b', ' ', 'a', 'p', 'l', '.', 't', 'n', 'c', 'h', 'T', 'd', 'o', 'u', 'j', 'm'}


In [62]:
# Hash tables
# A hash table is a sparse array (array that has empty cells).
# Each cell is called a slot.
# Each slot is associated with a key.
# The key is a unique identifier for the value.
# The value is the data that is stored in the slot.
# The hash function is a function that maps keys to slots.
# A hash collision occurs when two keys map to the same slot.
# It will try to resolve the collision.
# A slot can also be called a bucket.
# The load factor is the number of keys divided by the number of slots.
# The load factor is used to determine when to resize the hash table.
# Python tries to keep the load factor below 2/3.

num1 = 1
num2 = 1.0
print(num1 == num2)
hash(num1) == hash(num2) # True because num1 == num2


True


True

In [ ]:
# dicts are not space efficient. 
# Replacing dicts with tuples can reduce memory usage by 20-30%.

# "Optimization is the altar where maintainability is sacrificed."

In [ ]:
# MODIFYING THE CONTENTS OF A DICT WHILE ITERATING OVER IT IS A BAD IDEA.
# If Python decides to resize the hash table while you are iterating over it,
# your loop may not scan all items as expected!!

# If you need to scan and add or remove items from a dict,
# you can do it in two steps.
# Step 1: Scan the dict and collect the keys that need to be modified.
# Step 2: Modify the dict using the keys collected in step 1.


In [ ]:
# In Python 3, the keys(), items(), and values() methods of dict return "views" instead of lists.

In [ ]:
# The Named Tuple
# The collections.namedtuple function is a factory that produces subclasses of tuple enhanced with field names and a class name
# IMPORTANT: Instances of a class that you build with namedtuple takes exactly the SAME amount of memory as tuples because the field names are stored in the class, not the instance
# They use less memory than a regular object because they don't store attributes in a per-instance __dict__ dictionary

from collections import namedtuple
City = namedtuple('City', 'name country population coordinates')
tokyo = City('Tokyo', 'JP', 36.933, (35.689722, 139.691667))

# _fields is a useful attribute while _make() and _asdict() are useful class methods
