In [10]:
import collections
from random import choice

Card = collections.namedtuple('Card', ['rank','suit'])


class FrenchDeck:
    ranks = [str(n) for n in range(2, 11)] + list('JQKA')
    suits = 'spades diamonds clubs hearts'.split()

    def __init__(self):
        self._cards = [Card(rank, suit) for suit in self.suits
                                       for rank in self.ranks]
    
    def __len__(self):
        return len(self._cards)
    
    def __getitem__(self, position):
        return self._cards[position]
    
    def random_card(self):
        return choice(self._cards)

# Note: this FrenchDeck is immutable, because it only has __getitem__ and __len__ methods

In [ ]:
# list comprehension examples
[str(n) for n in range(2, 11)] + list('JQKA')
[Card(rank, suit) for suit in FrenchDeck.suits for rank in FrenchDeck.ranks]

In [ ]:
# __getitem__ example
deck = FrenchDeck()
print(f'Select index 5: {deck[5]}')

# benefits of implementing the __getitem__ method
print(f'Retrieve the first 3 cards: {deck[:3]}') # slicing
print(f'Pick cards by rank: {deck[12::13]}') # picking cards by rank

for card in deck: # iterting over the deck
    print(card)

In [ ]:
# random_choice example
print(deck.random_card())

In [22]:
# ranking and sorting the cards
suit_values = dict(spades=3, hearts=2, diamonds=1, clubs=0)
def spades_high(card):
    rank_value = FrenchDeck.ranks.index(card.rank) # get the index of the card rank 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, J, Q, K, A
    return rank_value * len(suit_values) + suit_values[card.suit] # multiply the rank value by the length of the suit values and add the suit value ex. 0 * 4 + 3 = 3

print("Sorted cards: ", [card for card in sorted(deck, key=spades_high)])

Sorted cards:  [Card(rank='2', suit='clubs'), Card(rank='2', suit='diamonds'), Card(rank='2', suit='hearts'), Card(rank='2', suit='spades'), Card(rank='3', suit='clubs'), Card(rank='3', suit='diamonds'), Card(rank='3', suit='hearts'), Card(rank='3', suit='spades'), Card(rank='4', suit='clubs'), Card(rank='4', suit='diamonds'), Card(rank='4', suit='hearts'), Card(rank='4', suit='spades'), Card(rank='5', suit='clubs'), Card(rank='5', suit='diamonds'), Card(rank='5', suit='hearts'), Card(rank='5', suit='spades'), Card(rank='6', suit='clubs'), Card(rank='6', suit='diamonds'), Card(rank='6', suit='hearts'), Card(rank='6', suit='spades'), Card(rank='7', suit='clubs'), Card(rank='7', suit='diamonds'), Card(rank='7', suit='hearts'), Card(rank='7', suit='spades'), Card(rank='8', suit='clubs'), Card(rank='8', suit='diamonds'), Card(rank='8', suit='hearts'), Card(rank='8', suit='spades'), Card(rank='9', suit='clubs'), Card(rank='9', suit='diamonds'), Card(rank='9', suit='hearts'), Card(rank='9', 

In [ ]:
from math import hypot

class Vector:
    def __init__(self, x=0, y=0):
        self.x = x
        self.y = y
        
    def __repr__(self):
        return f'Vector({self.x}, {self.y})'
    
    def __abs__(self):
        return hypot(self.x, self.y)
    
    def __bool__(self):
        return bool(abs(self))
    
    def __add__(self, other):
        x = self.x + other.x
        y = self.y +other.y
        return Vector(x, y=y)
    
    def __mul__(self, scalar):
        return Vector(self.x * scalar, self.y * scalar)
    
    
    
    

In [ ]:
# Sequences in Python

In [1]:
# List Comprehensions and Generator Expressions
alphabet = 'abcdefghijklmnopqrstuvwxyz'
alphabet_codes = [ord(letter) for letter in alphabet]
print(alphabet_codes)

[97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122]


In [9]:
# Tuples: Immutable? Yes, but only on the surface
# Tuple Unpacking
# parallel assignment - assigning items from an iterable to a tuple of variables, useful for swapping values of variables without a temporary variable
# Using * to grab excess items or when calling a function

a, b, *rest = range(5)
print(a, b, rest) # 0 1 [2, 3, 4]

[*range(4), 4] # 0, 1, 2, 3, 4
[range(4), 4] # [range(0, 4), 4]

0 1 [2, 3, 4]


[range(0, 4), 4]

In [ ]:
# Pattern matching with sequences

match subject:
    case <pattern_1>:
        <action_1>
    case <pattern_2>:
        <action_2>
    case <pattern_3>:
        <action_3>
    case _:
        <action_wildcard>

In [17]:
class Point:
    x: int
    y: int

    def __init__(self, x, y):
        self.x = x
        self.y = y

def location(point):
    match point:
        case Point(x=0, y=0):
            print("Origin is the point's location.")
        case Point(x=0, y=y):
            print(f"Y={y} and the point is on the y-axis.")
        case Point(x=x, y=0):
            print(f"X={x} and the point is on the x-axis.")
        case Point():
            print("The point is located somewhere else on the plane.")
        case _:
            print("Not a point")
            
point = Point(0,0)
location(point)

Origin is the point's location.


In [ ]:
# Example 2-9. Method from an imaginary Robot class


In [21]:
# Initializing a list with a certain number of nested lists
board = [['_'] * 3 for i in range(3)]
print(board)
weird_board = [['_'] * 3] * 3
print(weird_board)
weird_board[1][2] = 'O'
print(weird_board)

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]
[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]
[['_', '_', 'O'], ['_', '_', 'O'], ['_', '_', 'O']]


In [23]:
# Sorting

fruits = ['grape', 'raspberry', 'apple', 'banana']
sorted_fruits = sorted(fruits)
print(sorted_fruits)
print(fruits)
fruits.sort()
print(fruits)

fruits = ['grape', 'raspberry', 'apple', 'banana']
sorted_fruits_by_length = sorted(fruits, key=len)
print(sorted_fruits_by_length)

['apple', 'banana', 'grape', 'raspberry']
['grape', 'raspberry', 'apple', 'banana']
['apple', 'banana', 'grape', 'raspberry']
['grape', 'apple', 'banana', 'raspberry']


In [24]:
# Bisect - uses the binary search algorithm to find (bisect) and insert (insort) items in a sorted list. 
import bisect
import sys

HAYSTACK = [1,4,5,6,8,12,15,20,21,23,23,26,29,30]
NEEDLES = [0,1,2,5,8,10,22,23,29,30,31]

ROW_FMT = '{0:2d} @ {1:2d}    {2}{0:<2d}' # format for printing the needle, position, and offset

def demo(bisect_fn):
    for needle in reversed(NEEDLES):
        position = bisect_fn(HAYSTACK, needle) # search for the needle in the haystack
        offset = position * '  |' # create the offset
        print(ROW_FMT.format(needle, position, offset)) # print the needle, position, and offset

if __name__ == '__main__':
    if sys.argv[-1] == 'left':
        bisect_fn = bisect.bisect_left
    else:
        bisect_fn = bisect.bisect
    
    print('DEMO:', bisect_fn.__name__)
    print('haystack ->', ' '.join('%2d' % n for n in HAYSTACK))
    demo(bisect_fn)


DEMO: bisect_right
haystack ->  1  4  5  6  8 12 15 20 21 23 23 26 29 30
31 @ 14      |  |  |  |  |  |  |  |  |  |  |  |  |  |31
30 @ 14      |  |  |  |  |  |  |  |  |  |  |  |  |  |30
29 @ 13      |  |  |  |  |  |  |  |  |  |  |  |  |29
23 @ 11      |  |  |  |  |  |  |  |  |  |  |23
22 @  9      |  |  |  |  |  |  |  |  |22
10 @  5      |  |  |  |  |10
 8 @  5      |  |  |  |  |8 
 5 @  3      |  |  |5 
 2 @  1      |2 
 1 @  1      |1 
 0 @  0    0 


In [25]:
# Example 2-18. Given a test score, grade returns the corresponding letter grade
def grade(score, breakpoints=[60,70,80,90], grades='FDCBA'):
    i = bisect.bisect(breakpoints, score)
    return grades[i]

[grade(score) for score in [33, 99, 77, 70, 89, 90, 100]]

['F', 'A', 'C', 'C', 'B', 'A', 'A']

In [26]:
# Example 2-19. Insort keeps a sorted sequence always sorted
import bisect
import random

SIZE = 7

random.seed(1729)

my_list = []
for i in range(SIZE):
    new_item = random.randrange(SIZE*2)
    bisect.insort(my_list, new_item)
    print('%2d ->' % new_item, my_list)
    


10 -> [10]
 0 -> [0, 10]
 6 -> [0, 6, 10]
 8 -> [0, 6, 8, 10]
 7 -> [0, 6, 7, 8, 10]
 2 -> [0, 2, 6, 7, 8, 10]
10 -> [0, 2, 6, 7, 8, 10, 10]


In [ ]:
# Arrays
from array import array
from random import random

# Example 2-20. Creating, saving, and loading a large array of floats
floats = array('d', (random() for i in range(10**7))) # type code 'd' is for double-precision floating-point numbers
print(floats[-1])

fp = open('floats.bin', 'wb') # open the file in binary mode
floats.tofile(fp)
fp.close()

floats2 = array('d') # create an array of doubles
fp = open('floats.bin', 'rb')
floats2.fromfile(fp, 10**7) # read 10 million numbers from the binary file
fp.close()

print(floats2[-1])
print(floats2 == floats)

# saving with array.tofile and loading with array.fromfile is about 60 times faster than using 
# pickle.dump and pickle.load

0.1288579230853678
0.1288579230853678
True


In [32]:
# Memory View - built-in Python memoryview class is a shared-memory sequence type that lets you 
# handle slices of arrays without copying bytes

numbers = array('h', [-2, -1, 0, 1, 2]) # type code 'h' is for signed short integers
memv = memoryview(numbers) # create a memory view on the array of short integers
print(len(memv))

print(memv[0])

memv_oct = memv.cast('B') # create a memory view of unsigned bytes
memv_oct.tolist() # convert the memory view to a list of integers

memv_oct[5] = 4 # change the 6th byte in the unsigned bytes memory view
print(memv_oct)

5
-2


In [35]:
import numpy as np
# Basic Numpy Operations
a = np.arange(12)
print(a) # array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])
print(type(a)) # <class 'numpy.ndarray'>
print(a.shape) # (12,)

a.shape = 3, 4
print(a) # array([[ 0,  1,  2,  3], [ 4,  5,  6,  7], [ 8,  9, 10, 11]])
print(a[2]) # array([8, 9, 10, 11])
print(a[2,1]) # 9
print(a[:,1]) # array([1, 5, 9])
print(a.transpose()) # array([[ 0,  4,  8], [ 1,  5,  9], [ 2,  6, 10], [ 3,  7, 11]])
print(a.transpose().shape) # (4, 3)


[ 0  1  2  3  4  5  6  7  8  9 10 11]
<class 'numpy.ndarray'>
(12,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 8  9 10 11]
9
[1 5 9]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
(4, 3)


In [43]:
# Deques - double-ended queues
# Example 2-23. Working with a deque

from collections import deque
dq = deque(range(10), maxlen=10) # create a deque with 10 items
print(dq)
dq.rotate(3) # rotate the deque 3 steps to the right
print(dq) # deque([7, 8, 9, 0, 1, 2, 3, 4, 5, 6], maxlen=10)

dq.rotate(-4) 
print(dq) # deque([1, 2, 3, 4, 5, 6, 7, 8, 9, 0], maxlen=10)

dq.appendleft(-1) # add -1 to the left
print(dq) # deque([-1, 1, 2, 3, 4, 5, 6, 7, 8, 9], maxlen=10)

dq.extend([11, 22, 33])  # add three items to the right
print(dq) # deque([3, 4, 5, 6, 7, 8, 9, 11, 22, 33], maxlen=10)

dq.extendleft([10, 20, 30, 40]) # add four items to the left
print(dq) # deque([40, 30, 20, 10, 3, 4, 5, 6, 7, 8], maxlen=10)

# other queue libraries: queue, multiprocessing, asyncio, heapq, sched, and asyncio



deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], maxlen=10)
deque([7, 8, 9, 0, 1, 2, 3, 4, 5, 6], maxlen=10)
deque([1, 2, 3, 4, 5, 6, 7, 8, 9, 0], maxlen=10)
deque([-1, 1, 2, 3, 4, 5, 6, 7, 8, 9], maxlen=10)
deque([3, 4, 5, 6, 7, 8, 9, 11, 22, 33], maxlen=10)
deque([40, 30, 20, 10, 3, 4, 5, 6, 7, 8], maxlen=10)


In [ ]:
# The Named Tuple
# The collections.namedtuple function is a factory that produces subclasses of tuple enhanced with field names and a class name
# IMPORTANT: Instances of a class that you build with namedtuple takes exactly the SAME amount of memory as tuples because the field names are stored in the class, not the instance
# They use less memory than a regular object because they don't store attributes in a per-instance __dict__ dictionary

from collections import namedtuple
City = namedtuple('City', 'name country population coordinates')
tokyo = City('Tokyo', 'JP', 36.933, (35.689722, 139.691667))

# _fields is a useful attribute while _make() and _asdict() are useful class methods
